"""Initial migration - create all tables

Revision ID: 30f42b022536
Revises: 
Create Date: 2025-12-11 17:14:22.756347+00:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '30f42b022536'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('balance_view',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('friend_id', sa.Integer(), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('amount', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('user_id', 'friend_id', 'group_id', 'currency')
    )
    op.create_table('balances',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('friend_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('imported_from_splitwise', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('user_id', 'currency', 'friend_id')
    )
    op.create_table('cached_currency_rates',
    sa.Column('from', sa.String(length=3), nullable=False),
    sa.Column('to', sa.String(length=3), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('rate', sa.Float(), nullable=False),
    sa.Column('last_fetched', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('from', 'to', 'date')
    )
    op.create_table('expense_recurrences',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('job_id', sa.BigInteger(), nullable=False),
    sa.Column('notified', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('job_id')
    )
    op.create_table('group_balances',
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('firend_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.BigInteger(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('group_id', 'currency', 'user_id', 'firend_id')
    )
    op.create_table('push_notifications',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('subscription', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('email_verified', sa.DateTime(), nullable=True),
    sa.Column('image', sa.String(length=500), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('preferred_language', sa.String(length=10), nullable=False),
    sa.Column('banking_id', sa.String(length=255), nullable=True),
    sa.Column('obapi_provider_id', sa.String(length=255), nullable=True),
    sa.Column('hidden_friend_ids', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('verification_tokens',
    sa.Column('identifier', sa.String(length=255), nullable=False),
    sa.Column('token', sa.String(length=255), nullable=False),
    sa.Column('expires', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('identifier', 'token'),
    sa.UniqueConstraint('identifier', 'token', name='identifier_token_unique'),
    sa.UniqueConstraint('token')
    )
    op.create_table('accounts',
    sa.Column('id', sa.String(length=255), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('provider_account_id', sa.String(length=255), nullable=False),
    sa.Column('refresh_token', sa.Text(), nullable=True),
    sa.Column('access_token', sa.Text(), nullable=True),
    sa.Column('expires_at', sa.Integer(), nullable=True),
    sa.Column('token_type', sa.String(length=50), nullable=True),
    sa.Column('scope', sa.String(length=500), nullable=True),
    sa.Column('id_token', sa.Text(), nullable=True),
    sa.Column('session_state', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider', 'provider_account_id', name='provider_account_unique')
    )
    op.create_table('cached_bank_data',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('obapi_provider_id', sa.String(length=255), nullable=False),
    sa.Column('data', sa.Text(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('last_fetched', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('obapi_provider_id')
    )
    op.create_table('groups',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('public_id', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('default_currency', sa.String(length=3), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('splitwise_group_id', sa.String(length=255), nullable=True),
    sa.Column('simplify_debts', sa.Boolean(), nullable=False),
    sa.Column('archived_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('public_id'),
    sa.UniqueConstraint('splitwise_group_id')
    )
    op.create_table('sessions',
    sa.Column('id', sa.String(length=255), nullable=False),
    sa.Column('session_token', sa.String(length=255), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('expires', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_token')
    )
    op.create_table('expenses',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('paid_by', sa.Integer(), nullable=False),
    sa.Column('added_by', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=500), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('amount', sa.BigInteger(), nullable=False),
    sa.Column('split_type', sa.Enum('EQUAL', 'PERCENTAGE', 'EXACT', 'SHARE', 'ADJUSTMENT', 'SETTLEMENT', 'CURRENCY_CONVERSION', name='splittype'), nullable=False),
    sa.Column('expense_date', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('file_key', sa.String(length=500), nullable=True),
    sa.Column('group_id', sa.Integer(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('transaction_id', sa.String(length=255), nullable=True),
    sa.Column('recurrence_id', sa.Integer(), nullable=True),
    sa.Column('conversion_to_id', sa.String(length=36), nullable=True),
    sa.ForeignKeyConstraint(['added_by'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['conversion_to_id'], ['expenses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['deleted_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['paid_by'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['recurrence_id'], ['expense_recurrences.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('conversion_to_id')
    )
    op.create_index('idx_expense_group_id', 'expenses', ['group_id'], unique=False)
    op.create_index('idx_expense_paid_by', 'expenses', ['paid_by'], unique=False)
    op.create_table('group_users',
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('group_id', 'user_id')
    )
    op.create_table('expense_notes',
    sa.Column('id', sa.String(length=255), nullable=False),
    sa.Column('note', sa.Text(), nullable=False),
    sa.Column('created_by_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('expense_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['expense_id'], ['expenses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('expense_participants',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('expense_id', sa.String(length=36), nullable=False),
    sa.Column('amount', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['expense_id'], ['expenses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'expense_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('expense_participants')
    op.drop_table('expense_notes')
    op.drop_table('group_users')
    op.drop_index('idx_expense_paid_by', table_name='expenses')
    op.drop_index('idx_expense_group_id', table_name='expenses')
    op.drop_table('expenses')
    op.drop_table('sessions')
    op.drop_table('groups')
    op.drop_table('cached_bank_data')
    op.drop_table('accounts')
    op.drop_table('verification_tokens')
    op.drop_table('users')
    op.drop_table('push_notifications')
    op.drop_table('group_balances')
    op.drop_table('expense_recurrences')
    op.drop_table('cached_currency_rates')
    op.drop_table('balances')
    op.drop_table('balance_view')
    # ### end Alembic commands ###

